### ISSUE TITLE
need to define before and planning phases

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#17]
Despite the amount of the paper that describes PSP and TSP and lifecycles - I don't know what happens in the Before and Planning phases.  I don't know what this could be that isn't what is traditionally considered the Requirements phase.  Without this - I don't see how you can compare your results with other studies that would presumably consider these things as part of the requirements phase.  Meanwhile, a lot of the Project Phases section seems irrelevant to understanding the data.

**Comment by llayman** [comment]
I think this is a Bill question.

**Comment by timm** [comment]
i've sent an invite out to bill. when he accepts pz transfer this to bill

**Comment by WilliamNichols** [comment]
I can take this. I see two issues
1) uncertainty about the before and planning
2) a complaint that much of the phases section seems irrelevant. 

1) seems straightforward to deal with
2) does this mean the section should be trimmed?

**Comment by timm** [comment]
all we need here is a list of activities that happen in "before" and "planning".. just to satisfy the reviewers that (say) there is no "requirements" or other such in there.

**Comment by WilliamNichols** [comment]
How are these words?

TSP teams can be launched in any stage of the development lifecycle, though  are more common in the phases which require more staff. The TSP Launch Preparation scripts and checklists (see TSP: Leading a development Team) require the TSP coach to assure that management and business have clearly identified cost, schedule, and scope goals appropriate to the upcoming development activities, often including a conceptual model. For example an architecture team must have sufficient requirements to reason about, prototype, and specify an architecture (Integrate End to End Early and Often,  Software, IEEE  (Volume:30 ,  Issue: 4 ),  while a coding only team within a larger project would have more precisely defined requirements and high level design.
