### ISSUE TITLE
need to explain

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#18]
Bill: you got any comments on this:
- In Figure 10 - I have some very serious concerns about some of the data.  The most obvious example is that there are a large number of Before, Planning and Requirements errors being found during UnitTest.  I find this extremely unexpected. Unit testing should be focused on verifying a low level component in the context of very specific design requirements.  It is amazing that it would be so effective at discovering "Requirements" errors after those requirements have been through inspections and reviews during the requirements and design phase.  This is the most amazing thing I see in the data.  What is going on during unit testing?  

ignore this bit, just support text:
- Are people inappropriately tagging defects as "requirements" issues?   This data goes completely against the traditional "V" diagram that aligns System Test with Requirements, Integration Test with Design and Unit Test with Coding

**Comment by WilliamNichols** [comment]
You've been moving  much faster than me the past few days, I've been pinned down on some other urgent work.

Th is is a reasonable question. I can only guess. I do have access to item descriptions if we every want to follow up.
