### ISSUE TITLE
what is  \bar{x} and \tidle{x}?

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#23]
mean and standard deviation?

![image](https://cloud.githubusercontent.com/assets/29195/9021737/3b65e6ec-3821-11e5-8e63-ab60c30be041.png)

**Comment by WilliamNichols** [comment]
Possibly, what was the source? It looks like a survey and I’ve seldom approved of using means and standard deviations on ordinal scales. (it can be done, but I seldom see it done correctly.

**Comment by llayman** [comment]
Yes, they are means and standard deviations. Should I just use median?

**Comment by WilliamNichols** [comment]
I worked with a guy who did survey instruments in Northwestern and Minnesota Poly Sci departments. He always recommended using medians and modes for Likert scale questions unless you aggregate a number of questions. That leaves some issues of scale, but  aggregating the ranked ordinals from different questions to create a ratio value was accepted.  Standard deviations with hard 1-5 bounds typically aren’t very helpful. Interquartile range or other non-parametric makes more mathematic sense.  It’s also important to be clear if the data is mounded or double peaked.
