### ISSUE TITLE
been mercilessly pruning details from the TSP description

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#24]
bill--

worried you won't like the reduced description of TSP in this draft. now, space has to be made for the extra discussion points demanded by the reviewers. but i would not be surprised if you start adding back some of the culled details

**Comment by WilliamNichols** [comment]
I'll read it. Reducing the description won't cause me heartburn provided the readers understand what is going on. The article isn't a tutorial, there are other sources for that.

**Comment by timm** [comment]
I'll try and leave you, say, .25 to 0.5 of  a page to let you repair any inaccuracies introduced by my compression

**Comment by timm** [comment]
@WilliamNichols 
Bill- i'm going to close this issue. Feel free to re-open it if you think the current draft needs more notes on TSP.
