### ISSUE TITLE
fig9 confuses units on the y-axis

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#25]
@llayman : our plot is time to fix, there data is cost to fix. is this even repairable or should we dump this figure?

**Comment by WilliamNichols** [comment]
The difference is micro and macro.  At the macro level cost is in $ and time is in days. At the micro level cost is in developer man-hours. That is what we measure. Macro cost should correlate with man days except where there are collateral costs. For example, pushing updates is typically part of operations. Downtime can be a separate opportunity cost outside of the development costs.
