### ISSUE TITLE
meeting thurs june 16

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#30]
adas

**Comment by llayman** [comment]
Yes, I can write something.

**Comment by WilliamNichols** [comment]
Yes I can write

**Comment by timm** [comment]
- [x] @timm: point edtior to fshu;''s theory in intro

**Comment by timm** [comment]
@lucas add tlabelt o y-axis of fig1
- [x] @timm Done.

**Comment by timm** [comment]
- [x] @llayman: p4 comment

**Comment by timm** [comment]
- [x] split  fig13 into 50 and 90

**Comment by timm** [comment]
- [X] @timm: fix very last comment

**Comment by timm** [comment]
@lucas: make fig12 labels same as fig7
- [x] @timm: Done

**Comment by timm** [comment]
@timm: retire XXX in reviews
- [x] @llayman there is one remaining XXX

**Comment by timm** [comment]
- [x] @fshull: disconfirming in a forrest shull

**Comment by timm** [comment]
- [x] @llayman: reorg to improve early part of paper

**Comment by llayman** [comment]
- [x] @llayman: Update responses so that reviewers can find where they were referring to in the old paper

**Comment by lucas** [comment]
@timm I think you got the wrong guy, fyi
