### ISSUE TITLE
Section 4: I think the paragraphing could be improved 

### ISSUE THREAD

**Issue by llayman** [ai-se/phaseDelay#31]
Section 4: I think the paragraphing could be improved - the highly interesting point about agile is hidden. "A goal of agile methods is to reduce /---/ little empirical data exist" appears in the middle of a paragraph headed by "Shull et al. conducted a literature survey and held a series of e-workshops". Consider restructuring this section to bring forward the agile perspective.

**Comment by timm** [comment]
fixed
