### ISSUE TITLE
I don't fully understand Section 5.2.2 paragraph 4, and the relation between plan items and the time tracking logs.

### ISSUE THREAD

**Issue by llayman** [ai-se/phaseDelay#32]
I don't fully understand Section 5.2.2 paragraph 4, and the relation between plan items and the time tracking logs. "One or more defects are reported against a single plan item, e.g., a review session, an inspection meeting, a test execution". Multiple defects can be mapped to a plan item? But a plan item can also be "resolving a defect" (page 11:46). Also, the time tracking logs include time to collect data, prepare a fix, and its validation (page 12:50)… But what if a plan item includes both running a test suite and resolving the identified defect? The equation presented on page 13 suggests that the "time-to-fix a defect" could be inflated by e.g. running slow test cases. I'm sure the authors have all this covered, but the text confuses me. Could it possibly be revised? Maybe another figure could clarify the situation?

**Comment by WilliamNichols** [comment]
Action: consider how to clarify this text. I do not believe a figure will help unless we build a Con-Ops

**Comment by timm** [comment]
fixed by bill
