### ISSUE TITLE
Process clarifications in Section 5.2.3

### ISSUE THREAD

**Issue by llayman** [ai-se/phaseDelay#33]
Section 5.2.3: There is a minor discrepancy between Figure 7 and the text. In the running text you list system tests before acceptance tests, but the opposite order is depicted in the figure. Make sure the order is correct, also in Figure 13. To me acceptance testing normally happens as the final V&V step before release. Did all 171 projects really do system testing last? Maybe this is prescribed in TSP?

**Comment by WilliamNichols** [comment]
System test should precede acceptance test, this appears to be a plotting issue. Does it alter results?

**Comment by timm** [comment]
fixed
