### ISSUE TITLE
Section 6.1 - It is not obvious to me how to interpret "conformance with Benford distribution". 

### ISSUE THREAD

**Issue by llayman** [ai-se/phaseDelay#37]
Pretty sure this is a Bill line...

Section 6.1 - It is not obvious to me how to interpret "conformance with Benford distribution". Could you please elaborate somewhat?

**Comment by WilliamNichols** [comment]
Definitely mine. I will elaborate  in the text.  Benford is a distribution that occurs in many  natural contexts, but is almost impossible to achieve intentionally without a specific math algorithm. Deviations from a Benford are used in forensic accounting to show that data entries are being manipulated or  guessed.

**Comment by WilliamNichols** [comment]
action: either delete or explain that Benford is used in forensic accounting to distinguish data from a naturally occurring process from data intentionally invented by humans. THat is, the data was recorded in, more or less, real time or was at least representative of a real process with a vaguely log normal distribution
