### ISSUE TITLE
fix references

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#9]
Please check throughout your references, some include extended first name of authors, other only the initial.

**Comment by llayman** [comment]
Changed all to include first name.

W.E. Stephenson remains initials only because the original article doesn't have his/her first name.

**Comment by llayman** [comment]
Could not resolve reference for H.E. Dunsmore. I looked up this reference in online version of IEEE Software 1988 5(3) and no article in those page numbers is provided.

But the guy is Hubert E. (Buster) Dunsmore of Purdue
